name: UI-Test

on:
  push:
    branches:
      - master
      - rework
  pull_request:
    branches:
      - master
      - rework

  workflow_dispatch:

jobs:
  ui-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: UI tests + Macrobenchmark
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          profile: Pixel 2
          script: ./gradlew :treemap-chart-compose:connectedCheck :sample:android:macrobenchmark:connectedBenchmarkAndroidTest
